In [0]:
from google.colab import files
files.upload()

Saving Air-foil Self-Noise.csv to Air-foil Self-Noise.csv


{'Air-foil Self-Noise.csv': b'Frequency(in Hz),Angle Of Attack(In Degrees),Chord length(in meters),Free-stream velocity(in meters per second),Suction side displacement thickness(in meters), Scaled sound pressure level(in decibels)\r\n800,0,0.3048,71.3,0.00266337,126.201\r\n1000,0,0.3048,71.3,0.00266337,125.201\r\n1250,0,0.3048,71.3,0.00266337,125.951\r\n1600,0,0.3048,71.3,0.00266337,127.591\r\n2000,0,0.3048,71.3,0.00266337,127.461\r\n2500,0,0.3048,71.3,0.00266337,125.571\r\n3150,0,0.3048,71.3,0.00266337,125.201\r\n4000,0,0.3048,71.3,0.00266337,123.061\r\n5000,0,0.3048,71.3,0.00266337,121.301\r\n6300,0,0.3048,71.3,0.00266337,119.541\r\n8000,0,0.3048,71.3,0.00266337,117.151\r\n10000,0,0.3048,71.3,0.00266337,115.391\r\n12500,0,0.3048,71.3,0.00266337,112.241\r\n16000,0,0.3048,71.3,0.00266337,108.721\r\n500,0,0.3048,55.5,0.00283081,126.416\r\n630,0,0.3048,55.5,0.00283081,127.696\r\n800,0,0.3048,55.5,0.00283081,128.086\r\n1000,0,0.3048,55.5,0.00283081,126.966\r\n1250,0,0.3048,55.5,0.00283081

# **Exercise 1:-Restaurant Profit Prediction**

In [0]:
# Importing Libraries
import numpy as np
import pandas as pd
import sklearn
sklearn.__version__

'0.22.2.post1'

In [0]:
# Reading Dataset
data = pd.read_csv("/content/Restaurant_Profit_Data.csv")
data.head()

Miscellaneous_Expenses  Food_Innovation_Spend  ...     City     Profit
0               138671.80              167497.20  ...  Chicago  202443.83
1               153151.59              164745.70  ...   Mumbai  201974.06
2               102919.55              155589.51  ...    Tokyo  201232.39
3               120445.85              146520.41  ...  Chicago  193083.99
4                93165.77              144255.34  ...    Tokyo  176369.94

[5 rows x 5 columns]

In [0]:
# Check The Shape Of The Data
data.shape

(50, 5)

In [0]:
# Create Feature Matrix And Dependent Variable Vector
X = data.iloc[:,:-1].values
y = data.iloc[:,4].values

In [0]:
# Display Value Of Feature Matrix
X

array([[138671.8, 167497.2, 475918.1, 'Chicago'],
       [153151.59, 164745.7, 448032.53, 'Mumbai'],
       [102919.55, 155589.51, 412068.54, 'Tokyo'],
       [120445.85, 146520.41, 387333.62, 'Chicago'],
       [93165.77, 144255.34, 370302.42, 'Tokyo'],
       [101588.71, 134024.9, 366995.36, 'Chicago'],
       [148972.87, 136763.46, 131850.82, 'Mumbai'],
       [147304.06, 132446.13, 328010.68, 'Tokyo'],
       [150492.95, 122690.52, 315747.29, 'Chicago'],
       [110453.17, 125482.88, 309115.62, 'Mumbai'],
       [112368.11, 104061.08, 233294.95, 'Tokyo'],
       [93564.61, 102819.96, 253878.55, 'Mumbai'],
       [129094.38, 96011.75, 253973.44, 'Tokyo'],
       [137269.07, 94140.39, 256798.93, 'Mumbai'],
       [158321.42, 122091.24, 260646.92, 'Tokyo'],
       [124390.84, 116671.61, 265910.23, 'Chicago'],
       [123371.55, 80161.11, 268480.06, 'Mumbai'],
       [146851.58, 96805.16, 286708.31, 'Chicago'],
       [115949.79, 93897.16, 299053.57, 'Tokyo'],
       [155288.11, 88567.

In [0]:
# Display Value Of Dependent Variabel Vector
y

array([202443.83, 201974.06, 201232.39, 193083.99, 176369.94, 167173.12,
       166304.51, 165934.6 , 162393.77, 159941.96, 156303.95, 154441.4 ,
       151767.52, 144489.35, 142784.65, 140099.04, 137174.93, 135552.37,
       134448.9 , 132958.86, 128656.03, 121495.02, 120534.25, 118915.99,
       118734.04, 117586.34, 115915.54, 115190.31, 113464.38, 111186.64,
       110119.59, 107665.56, 107609.84, 106960.92, 106894.8 , 106661.51,
       100890.19, 100131.14,  91411.06,  91187.76,  88421.91,  87980.83,
        81680.49,  79940.98,  75382.33,  75108.08,  59672.75,  52741.73,
        45855.41,  24863.4 ])

In [0]:
# One Hot Encoding Of Categorical Column Called City
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
lblencoder = LabelEncoder()
X[:,3] = lblencoder.fit_transform(X[:,3]) 

In [0]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer


ct = ColumnTransformer(
    [('one_hot_encoder', OneHotEncoder(categories='auto'), [-1])],   # The column numbers to be transformed (here is [0] but can be [0, 1, 3])
    remainder='passthrough'                                         # Leave the rest of the columns untouched
)

X = ct.fit_transform(X)

In [0]:
# Display the feature matrix once the one hot encoding is done
X.astype(int)

array([[     1,      0,      0, 138671, 167497, 475918],
       [     0,      1,      0, 153151, 164745, 448032],
       [     0,      0,      1, 102919, 155589, 412068],
       [     1,      0,      0, 120445, 146520, 387333],
       [     0,      0,      1,  93165, 144255, 370302],
       [     1,      0,      0, 101588, 134024, 366995],
       [     0,      1,      0, 148972, 136763, 131850],
       [     0,      0,      1, 147304, 132446, 328010],
       [     1,      0,      0, 150492, 122690, 315747],
       [     0,      1,      0, 110453, 125482, 309115],
       [     0,      0,      1, 112368, 104061, 233294],
       [     0,      1,      0,  93564, 102819, 253878],
       [     0,      0,      1, 129094,  96011, 253973],
       [     0,      1,      0, 137269,  94140, 256798],
       [     0,      0,      1, 158321, 122091, 260646],
       [     1,      0,      0, 124390, 116671, 265910],
       [     0,      1,      0, 123371,  80161, 268480],
       [     1,      0,      0,

In [0]:
# Get rid of the dummy variable (column called Chicago)
X = X[:,1:]
# This step is not in Linear regression model

array([[0.0, 0.0, 138671.8, 167497.2, 475918.1],
       [1.0, 0.0, 153151.59, 164745.7, 448032.53],
       [0.0, 1.0, 102919.55, 155589.51, 412068.54],
       [0.0, 0.0, 120445.85, 146520.41, 387333.62],
       [0.0, 1.0, 93165.77, 144255.34, 370302.42],
       [0.0, 0.0, 101588.71, 134024.9, 366995.36],
       [1.0, 0.0, 148972.87, 136763.46, 131850.82],
       [0.0, 1.0, 147304.06, 132446.13, 328010.68],
       [0.0, 0.0, 150492.95, 122690.52, 315747.29],
       [1.0, 0.0, 110453.17, 125482.88, 309115.62],
       [0.0, 1.0, 112368.11, 104061.08, 233294.95],
       [1.0, 0.0, 93564.61, 102819.96, 253878.55],
       [0.0, 1.0, 129094.38, 96011.75, 253973.44],
       [1.0, 0.0, 137269.07, 94140.39, 256798.93],
       [0.0, 1.0, 158321.42, 122091.24, 260646.92],
       [0.0, 0.0, 124390.84, 116671.61, 265910.23],
       [1.0, 0.0, 123371.55, 80161.11, 268480.06],
       [0.0, 0.0, 146851.58, 96805.16, 286708.31],
       [0.0, 1.0, 115949.79, 93897.16, 299053.57],
       [0.0, 0.0, 155288

In [0]:
# Display the feature matrix after the Chicago column
X.astype(int)

array([[     0,      0, 138671, 167497, 475918],
       [     1,      0, 153151, 164745, 448032],
       [     0,      1, 102919, 155589, 412068],
       [     0,      0, 120445, 146520, 387333],
       [     0,      1,  93165, 144255, 370302],
       [     0,      0, 101588, 134024, 366995],
       [     1,      0, 148972, 136763, 131850],
       [     0,      1, 147304, 132446, 328010],
       [     0,      0, 150492, 122690, 315747],
       [     1,      0, 110453, 125482, 309115],
       [     0,      1, 112368, 104061, 233294],
       [     1,      0,  93564, 102819, 253878],
       [     0,      1, 129094,  96011, 253973],
       [     1,      0, 137269,  94140, 256798],
       [     0,      1, 158321, 122091, 260646],
       [     0,      0, 124390, 116671, 265910],
       [     1,      0, 123371,  80161, 268480],
       [     0,      0, 146851,  96805, 286708],
       [     0,      1, 115949,  93897, 299053],
       [     0,      0, 155288,  88567,   4134],
       [     1,     

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [0]:
len(X_train)

35

In [0]:
# Fitting Linear Regression Model To the Training set
from sklearn.linear_model import LinearRegression
MLR = LinearRegression()
MLR.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# Print The Constant and Coefficients
print(f'intercept = {MLR.intercept_}')
print(f'constant = {MLR.coef_}')

intercept = 51010.16100678094
constant = [-3.04799573e+02  1.58229418e+02  3.01968165e-02  7.90840255e-01
  3.10148566e-02]


In [0]:
# Predicting the test set results
y_predict = MLR.predict(X_test)

In [0]:
# Display actual and predicted values side by side
df = pd.DataFrame(data=y_test,columns=['actual'])
df['predicted'] = y_predict
df

actual      predicted
0   113464.38  114464.764722
1   154441.40  142718.884992
2   156303.95  144092.850078
3    87980.83   82766.774894
4   201232.39  190102.927619
5   115190.31  124731.310792
6    91411.06   76626.432613
7   107665.56  108586.968401
8   120534.25  124681.828086
9   176369.94  179549.506399
10  106960.92  106704.625400
11  106661.51   98222.671829
12  115915.54  121131.994055
13  106894.80  100601.189785
14  134448.90  138202.462501

In [0]:
# Predicting the single Observation Results.
singl_obs = [1,0,160349,134321,401400]
feature_array = np.array(singl_obs)
feature_array = feature_array.reshape(1,-1)
y_pred_single_obs = MLR.predict(feature_array)
round(float(y_pred_single_obs),2)

174223.21

In [0]:
from sklearn.metrics import r2_score
r_square = r2_score(y_test,y_predict)
print(r_square)

0.9358680970046418


# **Exercise 2:-Noise-Level Prediction**

In [0]:
# Reading Dataset
data = pd.read_csv("/content/Air-foil Self-Noise.csv")
data.head()

Frequency(in Hz)  ...   Scaled sound pressure level(in decibels)
0               800  ...                                    126.201
1              1000  ...                                    125.201
2              1250  ...                                    125.951
3              1600  ...                                    127.591
4              2000  ...                                    127.461

[5 rows x 6 columns]

In [0]:
# Checkig Data's Shape
data.shape

(1503, 6)

In [0]:
# Create Feature Matrix And Dependent Variable Vector
X = data.iloc[:,:-1].values
y = data.iloc[:,5].values

In [0]:
X

array([[ 800,    0,    0,   71,    0],
       [1000,    0,    0,   71,    0],
       [1250,    0,    0,   71,    0],
       ...,
       [4000,   15,    0,   39,    0],
       [5000,   15,    0,   39,    0],
       [6300,   15,    0,   39,    0]])

In [0]:
y

array([126.201, 125.201, 125.951, ..., 106.604, 106.224, 104.204])

In [0]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.3,random_state=0)

In [0]:
len(X_train)

1052

In [0]:
X_train

array([[ 500,    8,    0,   39,    0],
       [2000,   15,    0,   71,    0],
       [3150,   19,    0,   71,    0],
       ...,
       [1250,   22,    0,   71,    0],
       [1250,    5,    0,   55,    0],
       [1000,    9,    0,   31,    0]])

In [0]:
len(X_test)

451

In [0]:
len(y_train)

1052

In [0]:
len(y_test)

451

In [0]:
# Fitting Linear Regression Model To the Training set
from sklearn.linear_model import LinearRegression
MLR = LinearRegression()
MLR.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [0]:
# Print The Constant and Coefficients
print(f'intercept = {MLR.intercept_}')
print(f'constant = {MLR.coef_}')

intercept = 125.68778337155678
constant = [-0.00106705 -0.34310783  0.          0.08876919  0.        ]


In [0]:
# Predicting the test set results
y_predict = MLR.predict(X_test)

In [0]:
y_predict

array([121.31991788, 125.26799481, 121.6547148 , 125.73074376,
       124.17615901, 130.14326985, 125.27257421, 127.01568626,
       122.6840383 , 125.07842772, 126.75628972, 122.08158218,
       126.30553271, 124.61393142, 128.27315015, 122.83309505,
       130.08444082, 118.47930371, 123.33092426, 122.39338561,
       122.06227084, 122.6840383 , 122.70061076, 123.76978359,
       125.20548251, 124.93310138, 117.23199125, 129.37523167,
       127.12975645, 125.65704136, 126.73806472, 123.45401352,
       118.31008663, 124.45028638, 129.60261677, 124.72800162,
       119.8996108 , 109.27700836, 126.29727005, 124.67941772,
       128.43599334, 125.38574715, 122.2499009 , 117.71962246,
       120.70263442, 126.23480601, 130.79364998, 128.43599334,
       126.71030274, 127.5859901 , 123.89551522, 124.93782331,
       117.23199125, 126.62848022, 124.39221206, 125.61568204,
       114.91763097, 125.68097924, 126.34977346, 121.56368523,
       125.41421728, 127.21535652, 127.0074236 , 125.54

In [0]:
y_test

array([130.787, 119.541, 110.317, 117.396, 127.625, 121.66 , 118.689,
       130.026, 114.729, 124.207, 125.837, 131.518, 130.697, 117.809,
       126.661, 113.144, 126.758, 133.376, 118.084, 116.146, 123.46 ,
       130.086, 129.934, 120.657, 134.058, 122.089, 117.093, 138.758,
       130.829, 128.241, 128.952, 122.527, 103.38 , 126.406, 131.8  ,
       130.964, 119.253, 109.638, 127.781, 129.006, 132.54 , 125.484,
       138.274, 123.127, 111.029, 135.956, 127.122, 129.673, 125.647,
       129.235, 123.207, 126.995, 119.91 , 126.565, 121.527, 122.232,
       113.297, 128.338, 121.728, 118.904, 122.428, 133.235, 127.637,
       136.166, 124.356, 127.591, 128.354, 133.758, 132.127, 113.796,
       125.717, 126.086, 121.009, 130.05 , 126.648, 123.453, 122.086,
       126.514, 133.664, 130.183, 129.119, 128.412, 118.106, 122.797,
       127.314, 118.108, 128.809, 121.771, 134.528, 127.375, 130.989,
       127.117, 119.115, 110.652, 126.416, 107.284, 108.185, 136.103,
       120.509, 122.

In [0]:
# Display actual and predicted values side by side
df = pd.DataFrame(data=y_test,columns=['actual'])
df['predicted'] = y_predict
df

actual   predicted
0    130.787  121.319918
1    119.541  125.267995
2    110.317  121.654715
3    117.396  125.730744
4    127.625  124.176159
..       ...         ...
446  134.111  128.941047
447  115.321  117.449980
448  133.012  126.343257
449  128.647  129.856300
450  127.920  129.716451

[451 rows x 2 columns]

In [0]:
from sklearn.metrics import r2_score
r_square = r2_score(y_test,y_predict)
print(r_square)

0.320531083965769


In [0]:
MLR.score(X_train,y_train)

0.2497988978943808

In [0]:
print(y_predict[0:10])

[121.31991788 125.26799481 121.6547148  125.73074376 124.17615901
 130.14326985 125.27257421 127.01568626 122.6840383  125.07842772]


In [0]:
print(y_test[0:10])

[130.787 119.541 110.317 117.396 127.625 121.66  118.689 130.026 114.729
 124.207]


In [0]:
np.mean((y_predict - y_test))

0.07312252716205973